### ISSUE TITLE
dataProvider is null

### ISSUE THREAD

**Issue by gpeipman** [SPCSR/HelperFunctions#3] opened 2017-04-10 13:47 UTC
Hi!

I added search box, search results web part and script reference to my page. I configured things like said in guidance. When page then script is also loaded and on console I can see the following error: SCRIPT5007: Unable to get property 'get_properties' of undefined or null reference. This is because dataProvider is null.

Is there anything additional I should do to make this script work?

**Comment by wobba** [comment] 2017-04-10 17:11
Hi, can you pin down which section of the script, or the line?

**Comment by gpeipman** [comment] 2017-04-10 17:23
Line 610. Stack trace:

"TypeError: Unable to get property 'get_properties' of undefined or null reference
at injectCustomQueryVariables (https://mysite/test/SiteAssets/search.queryVariableInjector.js:318:26)
at Anonymous function (https://mysite/test/SiteAssets/search.queryVariableInjector.js:122:26)
at _fulfilled (https://mysite/test/SiteAssets/search.queryVariableInjector.js:1283:14)
at Anonymous function (https://mysite/test/SiteAssets/search.queryVariableInjector.js:1312:14)
at promise.promiseDispatch (https://mysite/test/SiteAssets/search.queryVariableInjector.js:1245:14)
at Anonymous function (https://mysite/test/SiteAssets/search.queryVariableInjector.js:1005:18)
at runSingle (https://mysite/test/SiteAssets/search.queryVariableInjector.js:586:14)
at flush (https://mysite/test/SiteAssets/search.queryVariableInjector.js:574:14)"

**Comment by gpeipman** [comment] 2017-04-10 17:32
There seems to be issue with timing, I think. I wrote a piece of testing code and it finds two query groups, one with data provider (your code finds group called MasterPage, this code finds MasterPage and Default):

SP.SOD.executeFunc("SP.js", "SP.ClientContext", function () {
	SP.SOD.executeFunc("SP.Search.js", "Microsoft.SharePoint.Client.Search.Query.KeywordQuery", function () {
		var queryGroups = Srch.ScriptApplicationManager.get_current().queryGroups;
		for (var group in queryGroups) {
			console.log("Query group: " + group);
			console.log(queryGroups[group]);
		}
	});
});

**Comment by wobba** [comment] 2017-04-10 19:02
Try specifying var RunOnWebParts = []; at the top of the script (line 86 in non-minified). Set it to ['Default'] to only run on the default search box/part on the page. Also read https://skodvinhvammen.wordpress.com/2015/11/30/how-to-connect-search-result-webparts-using-query-groups/ on how to specify the group name if you have multiple search parts on the page.

**Comment by wobba** [comment] 2017-04-12 21:38
@gpeipman I believe adding a check if a dataprovider is present on a group is the way to fix this, as all groups might not have one.

**Comment by wobba** [comment] 2017-04-12 21:41
@estruyf ..or timing and needing the executefunc. I think in my original code I had this, like in https://github.com/wobba/Scripts/blob/master/mAdcOW.OSSSearchResultOverride.js

**Comment by estruyf** [comment] 2017-04-13 08:29
@gpeipman did you by any chance configure your search web parts outside a search center on a page which already has a search box?

**Comment by gpeipman** [comment] 2017-04-13 08:31
Yes, that's correct. Custom page that needs search by synonyms, This page has search box and search results web part. I need to extend it later to search box shown on top of every page.

**Comment by estruyf** [comment] 2017-04-13 08:32
Ok, the problem is coming from the small search box most probably. Just tested and fixed this on my environment.

**Comment by estruyf** [comment] 2017-04-13 08:37
Fix has been pushed to the repo, can you test it out @gpeipman?

**Comment by gpeipman** [comment] 2017-04-18 06:19
Hi!
Thanks for fix. It seems to work okay now.

**Closed as completed** 2017-04-18 06:57 UTC
Labels: bug, enhancement
